### ISSUE TITLE
Fail to read and write hive tables with struct fields

### ISSUE THREAD

**Issue by killerwhile** [hortonworks-spark/spark-llap#234]
Hi Guys, Spark LLAP seems to have issues when reading or writing table with struct fields.

Versions:

HDP-2.6.2.14, with Hive (mysterious version 1.2.1000) in HTTP transport mode.
spark-llap-assembly_2.11:1.1.3-2.1
Spark 2.1.1.2.6.2.0-205-3.6

Steps to reproduce:

# Create Table and Insert Data

Using Spark-shell, without LLAP

```
SPARK_MAJOR_VERSION=2 spark-shell

// some imports
import org.apache.spark.sql.{Column, Dataset, Row}
import org.apache.spark.sql.types.DataTypes._
import org.apache.spark.sql.types._

// defining a complex schema
val schema=
StructType(
    Seq(
         StructField("structName", StructType(
            Seq(
             StructField("name", StringType), 
             StructField("weight", LongType),
             StructField("internalStruct", StructType(Seq(StructField("nick", StringType), StructField("age", IntegerType)))),
             StructField("internalMap", MapType(StringType,StringType,true)),
             StructField("internalMapWithArray", MapType(StringType,ArrayType(StringType, true),true)),
             StructField("internalArray", ArrayType(StringType,true))
             
            )
         )
        )
     ))

// instantiating some data 
val data = Seq(
   Row(Row("my", 1L,(Row("dog", 20)),
   Map("good_song" -> "darte un beso",
       "bad_song" -> "back it up"),
        Map("good_song" -> Array("tik tok", "timber"),
       "bad_song" -> Array("tik tok", "timber")),
       Array("1","2","3")

       ))
) 

// instantiating a df
val df = spark.createDataFrame(
  spark.sparkContext.parallelize(data),
  schema
)
// ensuring that I have what I defined.
df.printSchema()
// ensuring that I have what I defined (deuce)
df.show(false)

// Writing to Hive as ORC table
df.write.format("orc").option("orc.compress", "snappy").saveAsTable("test_llap_nested")
```

One can ensure using beeline that the data has been stored in Hive

```
echo "select * from test_llap_nested" | beeline -u '...'

+------------------------------+--+
|  test_llap_nested.structname  |
+------------------------------+--+
| {"name":"my","weight":1,"internalStruct":{"nick":"dog","age":20},"internalMap":{"bad_song":"back it up","good_song":"darte un beso"},"internalMapWithArray":{"bad_song":["tik tok","timber"],"good_song":["tik tok","timber"]},"internalArray":["1","2","3"]}  |
+------------------------------+--+
```

Redoing the same (after either drop the table or change table name) using LLAP is silently not inserting anything in the Hive table:

```
SPARK_MAJOR_VERSION=2 spark-shell --packages com.hortonworks.spark:spark-llap-assembly_2.11:1.1.3-2.1 --conf spark.sql.hive.llap=true

... same spark code as above ...
```

Beeline to validate: 
```
+-----------------------------+--+
| test_llap_nested.structname  |
+-----------------------------+--+
+-----------------------------+--+
```

# Query the Table

Using regular Spark, the snippet below works as expected:

```
SPARK_MAJOR_VERSION=2 spark-shell

// Query the table create above
val reread = spark.sqlContext.sql(s"select * from test_llap_nested")

// Ensure that my schema is what I wanted
reread.printSchema()

// Ensure that I have the same data
reread.show(false)
```

While using Spark LLAP, it raises the following exception:

```
18/05/30 13:19:35 WARN TaskSetManager: Stage 4 contains a task of very large size (268 KB). The maximum recommended task size is 100 KB.
18/05/30 13:19:37 ERROR Executor: Exception in task 0.0 in stage 4.0 (TID 12)
java.io.IOException: Received reader event error: Received submission failed event for fragment ID attempt_5496440955391100395_0119_0_00_000000_0
       	at org.apache.hadoop.hive.llap.LlapBaseRecordReader.next(LlapBaseRecordReader.java:172)
       	at org.apache.hadoop.hive.llap.LlapBaseRecordReader.next(LlapBaseRecordReader.java:48)
       	at org.apache.hadoop.hive.llap.LlapRowRecordReader.next(LlapRowRecordReader.java:121)
       	at org.apache.hadoop.hive.llap.LlapRowRecordReader.next(LlapRowRecordReader.java:68)
       	at org.apache.spark.rdd.HadoopRDD$$anon$1.getNext(HadoopRDD.scala:266)
       	at org.apache.spark.rdd.HadoopRDD$$anon$1.getNext(HadoopRDD.scala:211)
       	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:73)
       	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:39)
       	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
       	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
       	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
       	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
       	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
       	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:234)
       	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:228)
       	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:827)
       	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:827)
       	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
       	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
       	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
       	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
       	at org.apache.spark.scheduler.Task.run(Task.scala:99)
       	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Error while attempting to read chunk length
       	at org.apache.hadoop.hive.llap.io.ChunkedInputStream.read(ChunkedInputStream.java:78)
       	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
       	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
       	at java.io.FilterInputStream.read(FilterInputStream.java:83)
       	at org.apache.hadoop.hive.llap.LlapBaseRecordReader.hasInput(LlapBaseRecordReader.java:250)
       	at org.apache.hadoop.hive.llap.LlapBaseRecordReader.next(LlapBaseRecordReader.java:137)
       	... 25 more
Caused by: java.net.SocketException: Socket closed
       	at java.net.SocketInputStream.socketRead0(Native Method)
       	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
       	at java.net.SocketInputStream.read(SocketInputStream.java:170)
       	at java.net.SocketInputStream.read(SocketInputStream.java:141)
       	at java.net.SocketInputStream.read(SocketInputStream.java:223)
       	at java.io.DataInputStream.readInt(DataInputStream.java:387)
       	at org.apache.hadoop.hive.llap.io.ChunkedInputStream.read(ChunkedInputStream.java:68)
       	... 30 more
```

Thanks.

**Comment by EricWohlstadter** [comment]
StructType is supported on master for Spark 2.3/Hive 3. 
Closing this.
Please open a separate ticket if requesting for backport.
